### PR TITLE
change AUTO_UPDATE_DEFAULT to False

### PR DESCRIPTION
**Pull request by farahats9**
fixes issue #192

### CODE REVIEW

**Comment by KonstantinKorotaev** [comment]
Hi @farahats9 
Our default behavior right now is to support active learning.
Instead of changing default behavior you can use env variable AUTO_UPDATE. Set it as true and restart ML backend.

**Comment by farahats9** [comment]
@KonstantinKorotaev it is by default true due to the code and there is no way to set to false through environment variables, that's why it should be changed IMO.

**Review by KonstantinKorotaev — APPROVED** [review]

**Comment by Yakuho** [comment]
Maybe I found the reason why there is no way to set to false through environment variables...
I notice _wsgi.py by label-studio-ml init about lines 84~97
```python
    def parse_kwargs():
        param = dict()
        for k, v in args.kwargs:
            if v.isdigit():
                param[k] = int(v)
            elif v == 'True' or v == 'true':
                param[k] = True
            elif v == 'False' or v == 'False':
                param[k] = False
            elif isfloat(v):
                param[k] = float(v)
            else:
                param[k] = v
        return param
```
It should be ```elif v == 'False' or v == 'false':```, no ```elif v == 'False' or v == 'False':```

**Comment by Yakuho** [comment]
> Maybe I found the reason why there is no way to set to false through environment variables... I notice _wsgi.py by label-studio-ml init about lines 84~97
> 
> ```python
>     def parse_kwargs():
>         param = dict()
>         for k, v in args.kwargs:
>             if v.isdigit():
>                 param[k] = int(v)
>             elif v == 'True' or v == 'true':
>                 param[k] = True
>             elif v == 'False' or v == 'False':
>                 param[k] = False
>             elif isfloat(v):
>                 param[k] = float(v)
>             else:
>                 param[k] = v
>         return param
> ```
> 
> It should be `elif v == 'False' or v == 'false':`, no `elif v == 'False' or v == 'False':`

PR #256

**Pull request merged**
